#define MIN_PEPTIDE_MASS    500.0
#define MAX_PEPTIDE_MASS    6000
#define ALLOWED_MISSED_CLEAVAGES  2
#define MAX_LEN_PEPTIDE     100
#define MIN_LEN_PEPTIDE     6
#define MAX_LEN_DEFINITION  50
#define INITIAL_SEQ_LEN     1000
#define MAX_LEN_PROTEIN     5000
//#define SEMI_TRYPTIC        true
#define SEMI_TRYPTIC        false
